### ISSUE TITLE
Improve Icons SVG Stroke

### ISSUE THREAD

**Issue by DavideSegullo** [bitsongofficial/wallet-mobile#32]
We should improve icons SVG stroke, because on react native we have a bad rendering effect if we use opacity.

![photo5852970076104407974](https://user-images.githubusercontent.com/17269969/173543420-f0330340-8007-4db7-8576-f37c3771bde9.jpg)

**Comment by gabriele-pala** [comment]
@DavideSegullo 
At the moment we proceed with this solution, we use the color icons: #5B5B6D when they are disabled and #FFFFFF when you click on them and they are active.

**Comment by DavideSegullo** [comment]
Thank you @gabriele-pala , we can move it to development @zheleznov163, you can follow @gabriele-pala comment for the fix.

**Comment by zheleznov163** [comment]
I'm using icons exported from figma, with a few differences - I remove the inline stroke value, and the <g /> elements that are used for inline opacity. This is necessary to be able to manipulate the properties of the elements. Opacity is achieved by passing the HEX of the color with an alpha channel.

I noticed this shortcoming, and pointed out earlier that there is a problem. I'm creating a component that renders .svg and accepts a universal prop (stroke or fill, it doesn't matter. We agreed to use stroke).

In my experience, it's realistic (and practical) to create an SVG image that can accept a single color as any property, rather than trying to do complicated manipulations on each individual image in code.

**Comment by DavideSegullo** [comment]
Ye I agree with you, the only problem I can see is related with the opacity, as you can see on the icon for the translation. Ofc a solid color is the best way to solve, but probably we can improve the svg path

**Comment by DavideSegullo** [comment]
@zheleznov163 You can fix by using this hex color: #ACACEC
